#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
	ln -f -s /usr/share/emudesk/emudesk /usr/bin/emudesk

	if [ "systemd" == "$INITSYS" ]; then

		if [ -e /etc/systemd/system/emudesk.service ]; then
			rm /etc/systemd/system/emudesk.service /usr/lib/systemd/system/emudesk.service /usr/lib/systemd/user/emudesk.service >/dev/null  2>&1
		fi
		mkdir -p /usr/lib/systemd/system/
		cp /usr/share/emudesk/files/systemd/emudesk.service /usr/lib/systemd/system/emudesk.service
		# try fix error in Ubuntu 18.04
		# Failed to reload emudesk.service: Unit emudesk.service is not loaded properly: Exec format error.
		# /usr/lib/systemd/system/emudesk.service:10: Executable path is not absolute: pkill -f "emudesk --"
		if [ -e /usr/bin/pkill ]; then
			sed -i "s|pkill|/usr/bin/pkill|g" /usr/lib/systemd/system/emudesk.service
		fi
		systemctl daemon-reload
		systemctl enable emudesk
		systemctl start emudesk
	fi
fi
