name: Build Windows

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
  VCPKG_COMMIT_ID: "120deac3062162151622ca4860575a33844ba10b"
  VCPKG_DEFAULT_TRIPLET: "x64-windows-static"

jobs:
  build:
    name: x86_64-pc-windows-msvc
    runs-on: windows-2022
    steps:
    - name: Export GitHub Actions cache environment variables
      uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

    - name: Checkout source code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgDirectory: ${{ runner.workspace }}/vcpkg
        vcpkgGitCommitId: ${{ env.VCPKG_COMMIT_ID }}

    - name: Install vcpkg dependencies
      shell: pwsh
      run: |
        & "$env:VCPKG_ROOT/vcpkg" install --triplet x64-windows-static --x-install-root="$env:VCPKG_ROOT/installed"

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: x86_64-pc-windows-msvc

    - name: Show version information
      shell: bash
      run: |
        rustup -V
        cargo -V
        rustc -V
        cmake --version || true

    - uses: Swatinem/rust-cache@v2

    - name: Build
      shell: bash
      run: |
        cargo build --release --features inline --target=x86_64-pc-windows-msvc

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: emudesk-windows-x64
        path: target/x86_64-pc-windows-msvc/release/emudesk.exe
        if-no-files-found: error
